spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.107:8848
  rabbitmq:
    host: 192.168.0.107
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1
#redis连接配置
redis:
  ip: 192.168.0.107
  port: 6379
  password: redis
  timeout: 3000
  maxActive: 20
  maxIdle: 8
  maxWait: 1000
  testOnBorrow: true
  testOnReturn: true