spring:
  profiles:
    active: local
  application:
    name: goods-service

server:
  port: 8084

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

nacos:
  config:
    dataId: redis
    group: DEFAULT_GROUP
redis:
  stockKey: goods_stock
